### PR TITLE
Create tutorial.md

### PR DESCRIPTION
**Pull request by Pentelikon**
First draft of the tutorial in English to include in the main branch.

### CODE REVIEW

**Comment by ThijsRay** [comment]
Thank you for your pull request! I've put some of the commands from the tutorial in a script, which should reduce the amount of manual steps that are necessary to install the tool. I think the part about networking and missing system dependencies on the Raspberry Pi are still very relevant though, but the section with `.service` file, installing the Python dependencies and the modifying the configuration might be able to be replaced with invocations of the `make` command.

**Comment by Pentelikon** [comment]
Updated the commit to line up with the introduction of the 'make'-commands.

**Comment by Pentelikon** [comment]
Bump. :) If the tutorial is to your satisfaction, I can take down the old one and refer people here from now on.

**Comment by ThijsRay** [comment]
Thank you for your contribution!

**Pull request merged**
