### PR TITLE
Add RSA encryption for username and password

### PR DESCRIPTION
**Pull request by joep-nl**

### CODE REVIEW

**Comment by ThijsRay** [comment]
Hey, thank you for your merge request!

I do wonder what the added benefit of this change is, when all traffic is already served over HTTPS. With the current design, the server needs to process the username and password anyway. I don't see this changing anytime soon because it requires changes on Podimo's end. 

What benefits does adding RSA have that is not already covered by enforcing HTTPS?

**Comment by joep-nl** [comment]
At first I was thinking that it was a huge insecurity to place a password in the URL when accessing via a public network. But you are right, the URL's are hidden as long as you use HTTPS correctly.

Still it is advised to not send confidential information in (query) parameters of the URL.  For example: URL's are also often logged in access logs and stored in plain text. Also problems with HTTPS can occur or users can accidentally access the website via HTTP.  

The benefit of RSA is not as big as I expected, but it still adds some security. Removing the private key makes all the logs with the hashes useless. And it is a nice fallback if HTTPS is (accidentally) not used.

**Comment by koenrh** [comment]
Good point, @JoepdeJong! Request URIs will (inadvertently) end up end up in some logs, whether on the client (application logs) or remote server.

This could also be mitigated by using Basic authentication ([RFC 7617](https://datatracker.ietf.org/doc/html/rfc7617)), provided that you are using HTTPS. With Basic authentication, the client includes the username and password in the `Authorization` HTTP request header, which should never be logged.

Users would subscribe to a podcast using an URL like this:

`https://example%40example%2Ecom:password@podimo.thijs.sh/feed/12345-abcdef.xml`

Podcast client would turn this URL into an HTTP request like this (with the username and password base64 encoded, per the standard):

```
GET /feed/12345-abcdef.xml HTTP/1.1
Host: podimo.thijs.sh
Authorization: Basic ZXhhbXBsZUBleGFtcGxlLmNvbTpwYXNzd29yZAo=
```

Providing credentials through the `Authorization` HTTP request header and using HTTPS should prevent the Podimo credentials from being logged. 

I'm not sure if Basic authentication is widely supported, but at least Pocket Casts and Overcast[^1] seem to support it.

(I only just now found out about this project. Great work, @ThijsRay!)

[^1]: https://overcast.fm/podcasterinfo

**Comment by joep-nl** [comment]
> I'm not sure if Basic authentication is widely supported, but at least Pocket Casts and Overcast[1](#user-content-fn-1-fe3974443ce9de59f57b42626e6c633f) seem to support it.

I think basic authentication is not supported in more simple but widely used podcast apps like Apple Podcast. But it is a nice feature to add.

Besides that, @ThijsRay added some CORS headers yesterday, allowing a client-side web application to perform HTTP requests and retrieve the RSS feed. I use this in my personal podcast video player [moviepo](https://github.com/JoepdeJong/moviepo). Until now, I have to copy-paste the full link to the feed, including the username and password. Which makes everything less secure. Using an encrypted link would help a lot in the protection of my credentials.

**Comment by ThijsRay** [comment]
Thank you for the suggestion @koenrh! 

I do remember looking into Basic Authentication for the initial implementation, but my podcast player was not able to recognize it. This seems to be fixed now. I will add Basic Authentication as the default option.

**Pull request closed without merging**
